# Generated by Django 4.2.13 on 2024-08-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Project Images', 'verbose_name_plural': 'Project Images'},
        ),
    ]
