# Generated by Django 4.2.13 on 2024-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='', upload_to='team/'),
            preserve_default=False,
        ),
    ]
