# Generated by Django 4.2.13 on 2024-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
