# Generated by Django 4.2.13 on 2024-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='twitter_link',
            new_name='linkedin_link',
        ),
        migrations.AddField(
            model_name='settings',
            name='tiktok_link',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
