# Generated by Django 4.2.13 on 2024-05-22 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_twitter_link_settings_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'NewsLitter',
                'verbose_name_plural': 'NewsLitter',
            },
        ),
    ]
