# Generated by Django 4.2.13 on 2024-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='settings',
            name='email2',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone2',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
