# Generated by Django 4.2.13 on 2024-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_clients_options_rename_email_settings_email1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
