# Generated by Django 4.2.13 on 2024-08-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_settings_email2_alter_settings_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this title is display in slider in home page', max_length=150, verbose_name='title')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(help_text='this image is display in slider in home page', upload_to='homeImages/', verbose_name='image')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_image', to='settings.settings', verbose_name='home_image')),
            ],
            options={
                'verbose_name': 'Home Images',
                'verbose_name_plural': 'Home Images',
            },
        ),
    ]
