# Generated by Django 4.2.13 on 2024-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_do', models.TextField(max_length=5000)),
                ('our_mission', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
